spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/zlc?useUnicode=true&characterEncoding=utf8&useOldAliasMetadataBehavior=true&useTimezone=true&serverTimezone=GMT%2B8&useLegacyDatetimeCode=false&allowMultiQueries=true
    username: root
    password: 123456
#    username: sys
#    password: sys@1234
  redis:
    host: localhost
    port: 6379
    database: 2


# MyBatis
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.kking
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  #  mapperLocations: classpath*:mapper/**/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.kking: debug
server:
  compression:
    enabled: true
    mime-types: application/javascript,text/css,application/json,application/xml,text/html,text/xml,text/plain
  port: 8090
